module.exports.config = {
    name: "fyt",
    version: "1.0.0",
    hasPermssion: 2,
    credits: "... - Long LTD",
    description: "War In Chatbox",
    commandCategory: "wargroup",
    usages: "[fyt]",
    cooldowns: 7,
    dependencies: {
        "fs-extra": "",
        "axios": ""
    }
}

module.exports.run = async function({ api, args, Users, event}) {
 var mention = Object.keys(event.mentions)[0];
    
 let name =  event.mentions[mention];
    var arraytag = [];
        arraytag.push({id: mention});
    var a = function (a) { api.sendMessage(a, event.threadID); }
a("73R! 83H4N K4 9HUD4 M4RO9 ! G4NDU K4 BACHA 😝😝😝❤️😂😂TERI AMA KI KALI GAND MAROU 😂😂 CONDOMS LGA KY 😂😂😂❤️");
setTimeout(() => {a({body:"TERY BAJI KE CHUT KISI RANDI MA KA BACHY TERY MA KAA BHSDAA FADUU 😂😈" })}, 1000);
setTimeout(() => {a({body: "KI51 RA9D1 M9 K9 BA5H6Y 73R6Y M9 K3 5HU7 LU9 M9RO9 73R6Y GA9D M3I9 KI51 CHU76YI9 M9 K3 UL9D😘🌍😈✨" })}, 2000);
setTimeout(() => {a({body: "T3RY AM9 K9 BH9SD9 F9DU K151 RA9D1 M9 K9 B95H9😈💩" })}, 3000);
setTimeout(() => {a({body:"HERAA MANDI KE.UALD TERY MA KA 4THA YAR HO MEIN KSIS KUTY MA KA BACHY 😂😈💩"} )}, 4000);
setTimeout(() => {a({body: "BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN 😂😂😂😂CCCCCCHHHHHHOOOOOOOOODDDDDDDD GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU❤️❤️❤️❤️😂😂😂 ❤️❤️❤️" })}, 5000);
setTimeout(() => {a({body: "NON STOP FYTERR AP KA MAMA KA YAR FAHEEM😂🌍😘 AJ AP KE MA KE CHUT MARNA A RHA TERY BAI KE PHUDYY MEIN LULL KISI RAMDI MA KA DRYA BACHY TERY MA DE OHUDY CHAA JOHNY UNCLE DA LUN KISI GASHTYE MA DEYA BACHYA 😈😡🧸💩" })}, 6000);
setTimeout(() => {a({body: "😈[[=BHEAN KA LODA TERY MAAA KE CHUTT KISIS CHUTYIA MA KA BACHY=]]💩" })}, 7000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIII KISI GANDU MA KA BACHY :-)🧸 TERY MA KE CHUT KIS RANDI MA KA BACHY :,-) BHENA KA LODAA KISI SASTY MA KA BACHY :-P😈" })}, 8000);
setTimeout(() => {a({body: "😈[[=BHEAN KA LODA TERY MAAA KE CHUTT KISIS CHUTYIA MA KA BACHY=]]💩" })}, 9000);
setTimeout(() => {a({body: ":p :p :p :p :p :p :p :p🖕🏻🖕🏻🖕🏻🖕🏻 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMAAA UUUUUUNNNNNGGGGGLLLLLIIIIIII DDDDDDOIUUUUUUU 😂😂😂😂❤️❤️❤️🖕🏻🖕🏻🖕🏻" })}, 10000);
setTimeout(() => {a({body: "AAAAAA JAAAA TERYYY MAAA MEE CHUTT MEINN TERYYY CHOTAA BAHII DALONN RANDIIIII MAAAA KAAAA BACHYYYY 😆🦋🧸" })}, 12000);
setTimeout(() => {a({body: "K4R 9AT6YP3 :-*😀🦋 BHE9 K9 L9D9 😀🦋 73RY M9 K3 CH4U7 59 PA9I 9IK9L0N 😀🦋 K1SI R9D1 M9 D36Y9 BA5H6Y9🦋😀" })}, 14000);
setTimeout(() => {a({body: "TERY BAI KE CHUT 😆😈 TERY AMA KA BHOSDA UFF US KEIN HABSHYE KA LUN😆😈 TERY CHOTY BAI KE CHUT KEIN LUL KISI RANDI DEYA BACYHYA 8-)😍😘" })}, 16000);
setTimeout(() => {a({body: "TTTTEEEXXXXXIIIII KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU NNNNAASSAAAALLLL KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOOLLLLLLLLLLLAAAAAAAADDDDDD 😂😂😂😂😂❤️❤️❤️❤️😝" })}, 18000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA K K4R 9A T6YP3 :-*😀🦋 BHE9 K9 L9D9 😀🦋 73RY M9 K3 CH4U7 59 PA9I 9IK9L0N 😀🦋 K1SI R9D1 M9 D36Y9 BA5H6Y9🦋😀" })}, 20000);
setTimeout(() => {a({body: "🖕🏻🖕🏻🖕🏻🖕🏻 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMAAA UUUUUUNNNNNGGGGGLLLLLIIIIIII DDDDDDOIUUUUUUU 😂😂😂😂❤️❤️❤️🖕🏻🖕🏻🖕🏻HHHHHHHHHHHHHAAAAAAAARRRRRRRRRRAAAAAAAMMMMMMMMMMM KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOLLLLLLLLAAAAAAAAADDDDDD TTTTT333333RRRRRRRR111111 BBBBB33333HHHHHHHAAAAAANNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA PPPPPPUUUUUUUSSSHHHHH KEERRROOOOUUUU 😂😂😂😂❤️❤️❤️❤️TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD MAROU 😂😂😂😂❤️❤️❤️❤️❤️" })}, 22000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA K :-)😈M07H3R FU9K😂😆 734RY BA9J1 K3 5HU7 M319 LU9 :-O💋 73RY BAL9J1 K3 BR9Z3R M319 P91 DAL09 😆💋" })}, 25000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU 🥰🥰🥰🥰🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻☹️☹️☹️😝😝😝😝😝🤔🤔🤔🤔🤔😂😂😂😂" })} , 27000);
setTimeout(() => {a({body: "FAHEEM AKHTAR AP KE MA KE CHUTTT MEINN LUL DAL KR AP KE CHOTY SISTER PEDA KRA GA AP KE BHEAN KAA KALA PHUDA MEIN FAHEEM AKHTAR APNI LUND KA PANI DALA GA KISI BHEAN KA LODAA 😂😈😘" })} , 30000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIII TERYYYYYY BABAHIIIII KEEE GANDDD KAAAA SORAKHH MEIMNM FYTTT KRONNNNN GAAA ORRR FYTTT KRRR KRRR KAAA TERAAA BATHJIAAAAA PEDAAAA KRONNNN GAAAA :-D😈😂" })} , 34000);
setTimeout(() => {a({body: "[[=4AP K3 AM9 K9 BHOSD9 F9DU K1SI RA9D1 M9 K9 BA5H9Y=]]🙈😈😂😈M07H3R FU9K😂😆 734RY BA9J1 K3 5HU7 M319 LU9 :-O💋 73RY BAL9J1 K3 BR9Z3R M319 P91 DAL09 😆💋" })} , 38000);
setTimeout(() => {a({body: "FAHEEM AKHTAR AP KE MA KE CHUTTT MEINN LUL DAL KR AP KE CHOTY SISTER PEDA KRA GA AP KE BHEAN KAA KALA PHUDA MEIN FAHEEM AKHAR APNI LUND KA PANI DALA GA KISI BHEAN KA LODAA 😂😈😘" })} , 40000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU 🥰🥰🥰🥰🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻☹️☹️☹️😝😝😝😝😝🤔🤔🤔🤔🤔😂😂😂😂" })} , 43000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA K BETAAAAAAAAA NIKALLL JAAA YAAAA NAAA HOO TERYY BAJII KAA ABOSDAA FADD DUNN KISII RANDII KAA BACHYYYY 😆😂😈" })} , 46000);
setTimeout(() => {a({body: "<3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD CCCCCCHHHHHHOOOOOOOOODDDDDDDD DDDDDDOIUUUUUUU GGGGGGGGGAAAAAAAA MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN CCCCCCHHHHHHOOOOOOOOODDDDDDDD:p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p" })} , 48000);
setTimeout(() => {a({body: "😆😆😆😆😆😆😆😆😆😆😆👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅TTTTTTEEEEEEERRRRRRRRRRRUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋UU😋😋😋😋😋😋😋😋😋😋😋😋MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWKKKKKKKKKKKKKKOOOOOOOOOOOOOOOOOOOOOOOOOOOOO😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋XXXXXXXXXXXXXXXXXXXXXXXXXXXXHHHHHHHOOOOOODDDDDDDDDDDUUUUUUUUUUUUUUUUUUUUUUUUUU🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣BBBBIII*NNNNNNNNNNNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCCCCCOOOONNNNNNNNNNNNNDDDD" })} , 50000);
setTimeout(() => {a({body: "LLLLLOOOOOOOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣LL🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣BBBBBBBBBBBBHHHHHHHHHHHHHHNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN😋N😋N😋N😋N😋N😋N😋NN😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋KKKKKKKKKIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋LLLLLLLOOOOOOOOODDDDDDDDDDDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋"})} , 55000);
setTimeout(() => {a({body: "AAAAJAAAA TERYYYY BAJIII KEEE CHUTT MEINN LUN DALON 😈💋 AJAAAAAAA TERYYYY AMAAA MEEE CHUTTT FADUUUUU😙💋 AJAAAAA TUJHAAAAA MAMONNNNN BANYONNN RANDII KAAAAAA😒💋 AJAAAAAAAAAAAA TERYYYYY BAJIIIIII KOOOOOOOO TALAQQQQQQQ DAAAAAAAA KARRRRRRRR RANDAWAAAAAAAAAAAAAA KARONNNNNNNN😈😂😆💋" })} , 60000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA K BETAAAAAAAAA NIKALLL JAAA YAAAA NAAA HOO TERYY BAJII KAA ABOSDAA FADD DUNN KISII RANDII KAA BACHYYYY 😆😂😈" })}, 35000);
setTimeout(() => {a({body: ":-D😆KISIIIII CHUTYIAA MAAA DEYAAA BACHYAAA :,-)KISIII PANYAKHHHHHHH BAPPP DEEEEE ULADDDDDD:-P😂😒😆KISIIIIIIIII GAHSTYEEEE KANJRYYY MAAAA DEYAAAA BACHYAAAA :‑X🙄💋😆" })} , 65000);
setTimeout(() => {a({body: "AJAAA CHUDD DONNTSRY CHOTY BAJI KOOO AHHHHHAAAAAAA AJAAAAAAA RANDAWAAAA KRONNN TERYYY KHALAAA KEE BATHAJIIII KOOOOO🤕💋💋😂 AJAAAAAAAA GANDDDD MARONNN TERYYY BAHII KEEE RANDIII KAAAA BACHYYYY 💋🤕😆😂" })} , 800000);
setTimeout(() => {a({body: "LLLLLOOOOOOOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣LL🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣BBBBBBBBBBBBHHHHHHHHHHHHHHNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN😋N😋N😋N😋N😋N😋N😋NN😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋KKKKKKKKKIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋L" })} , 70000);
setTimeout(() => {a({body: "🅚︎🅘︎🅢︎🅘︎🅘︎🅘︎ 🅖︎🅐︎🅝︎🅓︎🅤︎🅤︎ 🅜︎🅐︎🅐︎ 🅐︎🅚︎🅐︎🅐︎🅐︎ 🅑︎🅐︎🅒︎🅗︎🅨︎🅨︎🅨︎ 🅢︎🅟︎🅔︎🅓︎🅓︎🅓︎🅓︎ 🅑︎🅗︎🅐︎🅡︎🅐︎🅐︎🅐︎🅐︎ 🅚︎🅘︎🅢︎🅘︎🅘︎🅘︎ 🅡︎🅐︎🅝︎🅓︎🅘︎🅘︎ 🅜︎🅐︎🅐︎🅐︎ 🅚︎🅐︎🅐︎🅐︎ 🅑︎🅐︎🅒︎🅗︎🅨︎🅨︎🅨︎🤣🥵👿" })} , 75000); 
setTimeout(() => {a({body: "T3R|| 84|-|9N K0K|_|T|Y45T4YL|\/|3 (_|-|0DU|\| R4N|=)|| K3  |)|N3 =D (y) (^^^)" })} , 78000);
setTimeout(() => {a({body: "73R!! M^44 K!! G49^D= 7^()^D= ^D=|_|9 83|-|39C|-|^()^D= K3 ^D=!!93 :DZ3ESHA9/_X3_5H4A9I_H3R3" })} , 80000);
setTimeout(() => {a({body: "__0Y3 T3R|| 84|-|3|\| 8|-|99G GY9N KY9 ❤😮]]:" })} , 83000);
setTimeout(() => {a({body: "__S4L3 J0K3R K3 B4(|-|3 T(_) M3R3 _||_ S3 4PN! M4 K! () K3S3 B4(|-|4Y3G4 T3R! M4 K0 T0 44J M3 (|-|0|) K3 M4N(_)NG4" })} , 86000);  
setTimeout(() => {a({body: "F33L K9R 73®|| B3|-|3N K3 L0D3 =D T3R|| M99 K|| (|-||_|T K3 |_|P9R K9||S3 T9B9DT0D L||K|-| R9|-|9 |-||_|N |_|S3 F33L K9R =D" })} , 88000);  
setTimeout(() => {a({body: "F33L K9R 73®|| B3|-|3N K3 L0D3 =D T3R|| M99 K|| (|-||_|T K3 |_|P9R K9||S3 T9B9DT0D L||K|-| R9|-|9 |-||_|N |_|S3 F33L K9R =D" })} , 90000);
setTimeout(() => {a({body: "T3R|| M99 K0 K|_|TT0N N3 (|-|0D D||Y9 T|-|9 T9B|-||| T0|-| T3R3 J9||S3 3K K|_|TT9 J9N9M L3 L||Y3 |_|SK3 K9L3 K9L3 B|-|0XD3 S3 :D" })} , 92000);
setTimeout(() => {a({body: "<3 CH99L 9UK99T BN99 R9NDII K3 B9CH3 T9R3 B9H3N K3 CHUT M99RUU T3R|| M99 K|| (|-||_|T M3 L0D9 D9L|_|N B3|-|3N K3 L0D3 (|-|9M9R K3 B9(|-|3 :D" })} , 94000); 
setTimeout(() => {a({body: "_(( D0ST)) _ (( M3 )) _  (( T3R3K0 )) _ (( J9NT9 )) _ (( HU )) _ (( TU.)) _ (( VH! )) _ (( HX )) _N9 (( J!SK!! )) _((  M99 ))__(( M3R3 )) , __(( L0D3 )) _ (( P3 )) _ (( SH3H9D )) _.(( LG9 )) _ (( K3 )) __(( CHUST! )) _ ((  HE))))" })} , 960000);  
setTimeout(() => {a({body: "<(￣︶￣)↗🐦.         S3x          (🙃)        S3 B|-|R9            M3R9.          D||L.         (❣️).       CH0DUG99.      D33V.   T3R||.       M99       K0.       PUR9.        D,||N      (😛)       ⟵(o_O)        🐥🟢" })} , 980000);
setTimeout(() => {a({body: "K4R 9A T6YP3 :-*😀🦋 BHE9 K9 L9D9 😀🦋 73RY M9 K3 CH4U7 59 PA9I 9IK9L0N 😀🦋 K1SI R9D1 M9 D36Y9 BA5H6Y9🦋😀" })} , 100000);
setTimeout(() => {a({body: "TERYYYYYY BABAHIIIII KEEE GANDDD KAAAA SORAKHH MEIMNM FYTTT KRONNNNN GAAA ORRR FYTTT KRRR KRRR KAAA TERAAA BATHJIAAAAA PEDAAAA KRONNNN GAAAA :-D😈😂" })} , 102000);
setTimeout(() => {a({body: "KISI GANDU MA KA BACHY :-)🧸 TERY MA KE CHUT KIS RANDI MA KA BACHY :,-) BHENA KA LODAA KISI SASTY MA KA BACHY :-P😈" })} , 104000);
setTimeout(() => {a({body: "BETAAAAAAAAA NIKALLL JAAA YAAAA NAAA HOO TERYY BAJII KAA ABOSDAA FADD DUNN KISII RANDII KAA BACHYYYY 😆😂😈" })} , 106000);
setTimeout(() => {a({body: "𝗞𝗜𝗦𝗜𝗜𝗜𝗜𝗜𝗜 𝗕𝗛𝗘𝗔𝗡𝗡𝗡 𝗞𝗔𝗔𝗔𝗔𝗔𝗔 𝗟𝗢𝗗𝗔𝗔𝗔𝗔𝗔𝗔 𝗧𝗬𝗣𝗘𝗘𝗘𝗘 𝗞𝗥𝗥𝗥 𝗠𝗔𝗔𝗔𝗔 𝗡𝗔𝗔𝗔𝗔𝗔 𝗖𝗛𝗨𝗗𝗪𝗔𝗔𝗔𝗔𝗔 𝗥𝗔𝗡𝗗𝗜𝗜𝗜𝗜 𝗞𝗔𝗔𝗔𝗔 𝗕𝗔𝗖𝗛𝗬𝗬𝗬𝗬𝗬😝👿🥵🤣" })} , 108000);
setTimeout(() => {a({body: "//G⃠A⃠N⃠D⃠U⃠U⃠U⃠ K⃠A⃠A⃠A⃠ B⃠A⃠C⃠H⃠Y⃠Y⃠Y⃠Y⃠ K⃠F⃠R⃠R⃠R⃠ N⃠A⃠A⃠A⃠A⃠A⃠A⃠A⃠ T⃠Y⃠P⃠E⃠E⃠E⃠ I⃠S⃠I⃠I⃠I⃠ R⃠N⃠A⃠D⃠I⃠I⃠I⃠ M⃠A⃠A⃠A⃠ K⃠A⃠A⃠ B⃠A⃠C⃠G⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠Y⃠🤣🥱😅" })} , 110000);
setTimeout(() => {a({body: "🅃🄴🅁🅈🅈🅈🅈🅈🅈 🄰🄼🄸🄸🄸🄸🄸 🄺🄴🄴🄴🄴🄴 🄱🅁🄰🅉🄴🅁🅁🅁🅁🅁 🄼🄴🄸🄽🄽🄽🄽🄽 🄲🄷🄰🅆🄰🄻🄻🄻🄻.🄳🄰🄻🄻🄻🄻 🄺🅁🅁🅁🅁🅁 🅃🅈🄹🄷🄰🄰🄰 🅃🄾🄵🄰🄰🄰🄰🄰🄰🄰🄰🄰 🄼🄴🄸🄽🄽🄽🄽🄽 🄳🄾🄽🄽🄽🄽🄽 🄱🄾🅃🄷🅈🄽🅈🅈🅈🅈 🄺🄰🄰🄰🄰🄰 🄱🄰🄲🄷🅈🅈🅈🅈🅈🅈🅈👿😝🤣😅 HERAA MANDI KE.UALD TERY MA KA 4THA YAR HO MEIN KSIS KUTY MA KA BACHY 😂😈💩 🅣︎🅔︎🅡︎🅨︎🅨︎🅨︎🅨︎🅨︎ 🅑︎🅐︎🅙︎🅘︎🅘︎🅘︎ 🅚︎🅔︎🅔︎🅔︎.🅖︎🅐︎🅝︎🅓︎🅓︎🅓︎ 🅜︎🅐︎🅡︎🅡︎🅡︎ 🅚︎🅡︎🅡︎🅡︎🅡︎🅡︎🅡︎🅡︎ 🅟︎🅡︎🅞︎🅝︎🅝︎ 🅗︎🅤︎🅑︎🅑︎🅑︎🅑︎ 🅞︎🅟︎🅟︎🅟︎🅔︎🅔︎🅔︎🅝︎🅝︎ 🅚︎🅡︎🅞︎🅝︎🅝︎🅝︎ 🅖︎🅐︎🅐︎🅐︎🅐︎🅐︎🅐︎🅐︎ 🅣︎🅔︎🅡︎🅨︎🅨︎🅨︎ 🅑︎🅐︎🅙︎🅘︎🅘︎ 🅚︎🅔︎🅔︎🅔︎🅔︎🅔︎ 🅑︎🅤︎🅝︎🅓︎🅗︎🅗︎🅗︎🅗︎ 🅜︎🅐︎🅡︎🅡︎🅡︎🅡︎🅡︎ 🅚︎🅐︎🅡︎🅡︎🅡︎🅡︎🅡︎🅡︎ 🅟︎🅔︎🅢︎🅐︎🅐︎🅐︎🅐︎🅐︎🅐︎ 🅚︎🅐︎🅜︎🅨︎🅞︎🅞︎🅞︎🅞︎🅝︎🅝︎🅝︎🅝︎🅝︎🅝︎ 🅖︎🅐︎🅐︎🅐︎🅐︎🅐︎🅐︎ 🅚︎🅘︎🅢︎🅘︎🅘︎🅘︎🅘︎🅘︎ 🅡︎🅐︎🅝︎🅓︎🅘︎🅘︎🅘︎🅘︎🅘︎ 🅜︎🅐︎🅐︎🅐︎🅐︎🅐︎ 🅚︎🅐︎🅐︎🅐︎🅐︎🅐︎ 🅑︎🅐︎🅒︎🅗︎🅨︎🅨︎🅨︎🅨︎🅨︎🅨︎🤣👿🥵" })} , 112000);
setTimeout(() => {a({body: "𝗞𝗜𝗦𝗜𝗜𝗜𝗜𝗜𝗜 𝗕𝗛𝗘𝗔𝗡𝗡𝗡 𝗞𝗔𝗔𝗔𝗔𝗔𝗔 𝗟𝗢𝗗𝗔𝗔𝗔𝗔𝗔𝗔 𝗧𝗬𝗣𝗘𝗘𝗘𝗘 𝗞𝗥𝗥𝗥 𝗠𝗔𝗔𝗔𝗔 𝗡𝗔𝗔𝗔𝗔𝗔 𝗖𝗛𝗨𝗗𝗪𝗔𝗔𝗔𝗔𝗔 𝗥𝗔𝗡𝗗𝗜𝗜𝗜𝗜 𝗞𝗔𝗔𝗔𝗔 𝗕𝗔𝗖𝗛𝗬𝗬𝗬𝗬𝗬😝👿🥵🤣" })} , 114000);
setTimeout(() => {a({body: "KISIIIII RANDII MAAA KAAA BACHYYY 😂💋😂TERYYYY BAJI KEEE CHUTTT 😈😂😆TERYYY AMAA KAAA BAOBEXXX MEINN LUNNN😈😆💋😂TERYYYYY BABHII KAAA BRAAAAA KEIN PANIII DALONNNN😆😂😈😆" })} , 116000);
setTimeout(() => {a({body: "AJAAA CHUDD DONNTSRY CHOTY BAJI KOOO AHHHHHAAAAAAA AJAAAAAAA RANDAWAAAA KRONNN TERYYY KHALAAA KEE BATHAJIIII KOOOOO🤕💋💋😂 AJAAAAAAAA GANDDDD MARONNN TERYYY BAHII KEEE RANDIII KAAAA BACHYYYY 💋🤕😆😂" })} , 118000);
setTimeout(() => {a({body: "FAHEEM AKHTAR AP KE MA KE CHUTTT MEINN LUL DAL KR AP KE CHOTY SISTER PEDA KRA GA AP KE BHEAN KAA KALA PHUDA MEIN FAHEEM AKHTAR APNI LUND KA PANI DALA GA KISI BHEAN KA LODAA 😂😈😘" })} , 120000);
setTimeout(() => {a({body: "BETAAAAAAAAA NIKALLL JAAA YAAAA NAAA HOO TERYY BAJII KAA ABOSDAA FADD DUNN KISII RANDII KAA BACHYYYY 😆😂😈" })} , 122000);
setTimeout(() => {a({body: "[[=4AP K3 AM9 K9 BHOSD9 F9DU K1SI RA9D1 M9 K9 BA5H9Y=]]🙈😈😂" })} , 124000);
setTimeout(() => {a({body: "AAAAJAAAA TERYYYY BAJIII KEEE CHUTT MEINN LUN DALON 😈💋 AJAAAAAAA TERYYYY AMAAA MEEE CHUTTT FADUUUUU😙💋 AJAAAAA TUJHAAAAA MAMONNNNN BANYONNN RANDII KAAAAAA😒💋 AJAAAAAAAAAAAA TERYYYYY BAJIIIIII KOOOOOOOO TALAQQQQQQQ DAAAAAAAA KARRRRRRRR RANDAWAAAAAAAAAAAAAA KARONNNNNNNN😈😂😆💋" })} , 126000);
setTimeout(() => {a({body: "FAHEEM AP KE MA KE CHUTTT MEINN LUL DAL KR AP KE CHOTY SISTER PEDA KRA GA AP KE BHEAN KAA KALA PHUDA MEIN FAHEEM AKHTAR APNI LUND KA PANI DALA GA KISI BHEAN KA LODAA 😂😈😘" })} , 128000);
setTimeout(() => {a({body: "TERYYY AMAAAA KAAAA BOBEXXXX KOOOO LALLLLL KRONNNN RANDIIII MAAAAA KAAAAA BACHYYY😈😂" })} , 130000);
setTimeout(() => {a({body: "FAHEEM AP KE MA KE CHUTTT MEINN LUL DAL KR AP KE CHOTY SISTER PEDA KRA GA AP KE BHEAN KAA KALA PHUDA MEIN FAHEEM AKHTAR APNI LUND KA PANI DALA GA KISI BHEAN KA LODAA 😂😈😘" })} , 132000);
setTimeout(() => {a({body: "TERY BAI KE CHUT 😆😈 TERY AMA KA BHOSDA UFF US KEIN HABSHYE KA LUN😆😈 TERY CHOTY BAI KE CHUT KEIN LUL KISI RANDI DEYA BACYHYA 8-)😍😘" })} , 134000);
setTimeout(() => {a({body: "TERYYY AMAAAA KAAAA BOBEXXXX KOOOO LALLLLL KRONNNN RANDIIII MAAAAA KAAAAA BACHYYY😈😂" })} , 136000);
setTimeout(() => {a({body: "AAAAAA JAAAA TERYYY MAAA MEE CHUTT MEINN TERYYY CHOTAA BAHII DALONN RANDIIIII MAAAA KAAAA BACHYYYY 😆🦋🧸" })} , 138000);
setTimeout(() => {a({body: "K151 Y973EM M9 D3Y9 BA5H6Y 73R6Y K9 K3 5HU7 M3I9 LU9 KI51 RA9D1 D36Y BA5H6Y:-)😂 73RY B9J1 K3 5HU7 M319 LU9 BH39 K9 L0D9 8-)😘" })} , 140000);
setTimeout(() => {a({body: "KISI GANDU MA KA BACHY :-)🧸 TERY MA KE CHUT KIS RANDI MA KA BACHY :,-) BHENA KA LODAA KISI SASTY MA KA BACHY :-P😈" })} , 142000);
setTimeout(() => {a({body: "😈[[=BHEAN KA LODA TERY MAAA KE CHUTT KISIS CHUTYIA MA KA BACHY=]]💩" })} , 144000);
setTimeout(() => {a({body: "NON STOP FYTERR AP KA MAMA KA YAR FAHEEM😂🌍😘 AJ AP KE MA KE CHUT MARNA A RHA TERY BAI KE PHUDYY MEIN LULL KISI RAMDI MA KA DRYA BACHY TERY MA DE OHUDY CHAA JOHNY UNCLE DA LUN KISI GASHTYE MA DEYA BACHYA 😈😡🧸💩" })} , 146000);
setTimeout(() => {a({body: "TERY BAI KE CHUT 😆😈 TERY AMA KA BHOSDA UFF US KEIN HABSHYE KA LUN😆😈 TERY CHOTY BAI KE CHUT KEIN LUL KISI RANDI DEYA BACYHYA 8-)😍😘" })} , 148000);
setTimeout(() => {a({body: "T3RY AM9 K9 BH9SD9 F9DU K151 RA9D1 M9 K9 B95H9😈💩" })} , 150000);
setTimeout(() => {a({body: "KI51 RA9D1 M9 K9 BA5H6Y 73R6Y M9 K3 5HU7 LU9 M9RO9 73R6Y GA9D M3I9 KI51 CHU76YI9 M9 K3 UL9D😘🌍😈✨" })} , 152000);
setTimeout(() => {a({body: "AAAAAA JAAAA TERYYY MAAA MEE CHUTT MEINN TERYYY CHOTAA BAHII DALONN RANDIIIII MAAAA KAAAA BACHYYYY 😆🦋🧸" })} , 154000);
setTimeout(() => {a({body: "T3R|| M99 K0 K|_|TT0N N3 (|-|0D D||Y9 T|-|9 T9B|-||| T0|-| T3R3 J9||S3 3K K|_|TT9 J9N9M L3 L||Y3 |_|SK3 K9L3 K9L3 B|-|0XD3 S3 :D " })} , 156000);
setTimeout(() => {a({body: "):^)^_^(^^)o:-)B-)8-):,-):-D}:‑););-):-$:-!:-P:-*:‑X:-|:-\:-[=_=(TT(:-(>.<(+)(*_*)O_o*\0:-\:-\:-$:-Do:-)(/*:0=-O:-O(^^)o:-);-):-$:-[=_=O_o*\0*:0(*_*:-):^)^_^(^^)o:-)B-)8-):,-):-D}:‑););-):-$:-!:-P:-*:‑X:-|:-\:-[=_=(TT):'(:-(>.<(+_+)(*_*)O_o*\0o:-)^_^/*:0=-O:-O(^^)o:-);-):-$:-[=_=O_o*\(TT):-\:-!;)B-)^_^:^)8-)}:‑):-P:-|:'((+_+)=-O:-):,-):-D:-*:‑X:-(>.<:-OB-)B-))(TT):-\:-!;)B-)^_^:^)8-)}:‑):-P:-|:'((+8-_+)=-O:-):,-):-D:-*:‑X:-(>.<:-O^_^o:" })} , 158000);
setTimeout(() => {a({body: "__S4L3 J0K3R K3 B4(|-|3 T(_) M3R3 _||_ S3 4PN! M4 K! () K3S3 B4(|-|4Y3G4 T3R! M4 K0 T0 44J M3 (|-|0|) K3 M4N(_)NG4" })} , 160000);
setTimeout(() => {a({body: ":-)😈M07H3R FU9K😂😆 734RY BA9J1 K3 5HU7 M319 LU9 :-O💋 73RY BAL9J1 K3 BR9Z3R M319 P91 DAL09 😆💋" })} , 162000);
setTimeout(() => {a({body: "FAHEEM AP KE MA KE CHUTTT MEINN LUL DAL KR AP KE CHOTY SISTER PEDA KRA GA AP KE BHEAN KAA KALA PHUDA MEIN FAHEEM AKHTAR APNI LUND KA PANI DALA GA KISI BHEAN KA LODAA 😂😈😘" })} , 164000); 


  }